#!name=YouTube Premium 2025 - Nightmarket
#!desc=Chặn quảng cáo YouTube + Music | Hỗ trợ PiP, phụ đề & phát nền | Yêu cầu bật bảo vệ QUIC
#!tag=Chặn quảng cáo, YouTube, Music, PiP
# 👤 Author: : @Nightmarket Server , @Maasea
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Nightmarket Server  
#!name=Test HTML Inject

[Script]

Test = https://raw.githubusercontent.com/NightmarketServer/Youtube-Premium/refs/heads/main/testgg.js
